<script setup lang="ts">
import { CalendarDays, CircleHelp, DollarSign, LayoutDashboard, Settings, Users, WandSparkles, type LucideIcon } from 'lucide-vue-next'
import { RouterLink } from 'vue-router'
withDefaults(defineProps<{ mobile?: boolean }>(), { mobile: false })
interface NavItem { label: string; icon: LucideIcon; to: string }
const topItems: NavItem[] = [{ label: 'Visão geral', icon: LayoutDashboard, to: '/' }, { label: 'Agenda', icon: CalendarDays, to: '/agenda' }, { label: 'Financeiro', icon: DollarSign, to: '/financeiro' }, { label: 'Automações', icon: WandSparkles, to: '/automacoes' }, { label: 'Usuários', icon: Users, to: '/usuarios' }]
const bottomItems: NavItem[] = [{ label: 'Ajuda', icon: CircleHelp, to: '/ajuda' }, { label: 'Configurações', icon: Settings, to: '/configuracoes/atendimentos' }]
</script>
<template><aside :class="mobile ? 'flex h-auto w-full flex-row items-start border-0 px-5 py-4' : 'hidden h-full w-[68px] shrink-0 flex-col items-center border-r border-[var(--color-border)] bg-white py-5 md:flex'"><nav class="flex flex-col items-center gap-3" :class="mobile ? 'flex-row' : ''" aria-label="Navegação principal"><RouterLink v-for="item in topItems" :key="item.label" :to="item.to" :aria-label="item.label" :title="item.label" class="rounded-xl p-3 text-neutral-400 transition hover:bg-neutral-100 hover:text-neutral-700" active-class="bg-[var(--color-primary)] text-neutral-900"><component :is="item.icon" :size="19" stroke-width="1.8" /></RouterLink></nav><nav class="flex flex-col items-center gap-3" :class="mobile ? 'ml-auto flex-row' : 'mt-auto'" aria-label="Navegação secundária"><RouterLink v-for="item in bottomItems" :key="item.label" :to="item.to" :aria-label="item.label" :title="item.label" class="rounded-xl p-3 text-neutral-400 transition hover:bg-neutral-100 hover:text-neutral-700" active-class="bg-[var(--color-primary)] text-neutral-900"><component :is="item.icon" :size="19" stroke-width="1.8" /></RouterLink><div class="flex h-9 w-9 items-center justify-center rounded-full bg-neutral-800 text-xs font-medium text-white" aria-label="Perfil">GL</div></nav></aside></template>
