<script setup lang="ts">
import { reactive, watch } from 'vue'
import BaseButton from '../ui/BaseButton.vue'
import BaseModal from '../ui/BaseModal.vue'
import type { Appointment, AppointmentInput } from '../../types/appointment'
const props = defineProps<{ open: boolean; appointment?: Appointment | null }>()
const emit = defineEmits<{ close: []; save: [input: AppointmentInput] }>()
const form = reactive<AppointmentInput>({ name: '', modality: 'online', durationMinutes: 60, displayIntervalMinutes: 30, recurrence: 'none' })
const errors = reactive({ name: '', duration: '' })
watch(() => [props.open, props.appointment], () => { if (props.open) Object.assign(form, props.appointment ? { name: props.appointment.name, modality: props.appointment.modality, durationMinutes: props.appointment.durationMinutes, displayIntervalMinutes: props.appointment.displayIntervalMinutes, recurrence: props.appointment.recurrence } : { name: '', modality: 'online', durationMinutes: 60, displayIntervalMinutes: 30, recurrence: 'none' }) }, { deep: true })
function submit() { errors.name = form.name.trim() ? '' : 'Informe um nome'; errors.duration = form.durationMinutes > 0 ? '' : 'Informe uma duração válida'; if (!errors.name && !errors.duration) emit('save', { ...form, name: form.name.trim() }) }
</script>
<template><BaseModal :open="open" :title="appointment ? 'Editar atendimento' : 'Novo tipo de atendimento'" @close="emit('close')"><form class="space-y-5" @submit.prevent="submit"><label class="block text-sm"><span class="mb-2 block font-medium">Nome do atendimento</span><input v-model="form.name" class="w-full rounded-lg border border-[var(--color-border)] px-3 py-2.5" placeholder="Ex.: Consulta inicial" /><span v-if="errors.name" class="mt-1 block text-xs text-red-600">{{ errors.name }}</span></label><label class="block text-sm"><span class="mb-2 block font-medium">Modalidade</span><select v-model="form.modality" class="w-full rounded-lg border border-[var(--color-border)] bg-white px-3 py-2.5"><option value="online">Online</option><option value="in_person">Presencial</option></select></label><div class="grid grid-cols-2 gap-3"><label class="block text-sm"><span class="mb-2 block font-medium">Duração (minutos)</span><input v-model.number="form.durationMinutes" type="number" min="1" class="w-full rounded-lg border border-[var(--color-border)] px-3 py-2.5" /><span v-if="errors.duration" class="mt-1 block text-xs text-red-600">{{ errors.duration }}</span></label><label class="block text-sm"><span class="mb-2 block font-medium">Intervalo de exibição</span><select v-model.number="form.displayIntervalMinutes" class="w-full rounded-lg border border-[var(--color-border)] bg-white px-3 py-2.5"><option :value="15">15 minutos</option><option :value="30">30 minutos</option><option :value="45">45 minutos</option><option :value="60">60 minutos</option></select></label></div><label class="block text-sm"><span class="mb-2 block font-medium">Recorrência</span><select v-model="form.recurrence" class="w-full rounded-lg border border-[var(--color-border)] bg-white px-3 py-2.5"><option value="none">Sem recorrência</option><option value="weekly">Semanal</option><option value="biweekly">Quinzenal</option><option value="monthly">Mensal</option></select></label><div class="flex justify-end gap-3 pt-2"><BaseButton variant="secondary" @click="emit('close')">Cancelar</BaseButton><BaseButton type="submit">Salvar atendimento</BaseButton></div></form></BaseModal></template>
